/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiWorkbenchRouteImport } from './routes/ai-workbench'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as QualityRouteImport } from './routes/quality'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWorkbenchRoute = AiWorkbenchRouteImport.update({
  id: '/ai-workbench',
  path: '/ai-workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-workbench': typeof AiWorkbenchRoute
  '/crm': typeof CrmRoute
  '/inventory': typeof InventoryRoute
  '/procurement': typeof ProcurementRoute
  '/quality': typeof QualityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-workbench': typeof AiWorkbenchRoute
  '/crm': typeof CrmRoute
  '/inventory': typeof InventoryRoute
  '/procurement': typeof ProcurementRoute
  '/quality': typeof QualityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-workbench': typeof AiWorkbenchRoute
  '/crm': typeof CrmRoute
  '/inventory': typeof InventoryRoute
  '/procurement': typeof ProcurementRoute
  '/quality': typeof QualityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ai-workbench' | '/crm' | '/inventory' | '/procurement' | '/quality'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/ai-workbench' | '/crm' | '/inventory' | '/procurement' | '/quality'
  id:
    | '__root__'
    | '/'
    | '/ai-workbench'
    | '/crm'
    | '/inventory'
    | '/procurement'
    | '/quality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiWorkbenchRoute: typeof AiWorkbenchRoute
  CrmRoute: typeof CrmRoute
  InventoryRoute: typeof InventoryRoute
  ProcurementRoute: typeof ProcurementRoute
  QualityRoute: typeof QualityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-workbench': {
      id: '/ai-workbench'
      path: '/ai-workbench'
      fullPath: '/ai-workbench'
      preLoaderRoute: typeof AiWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiWorkbenchRoute: AiWorkbenchRoute,
  CrmRoute: CrmRoute,
  InventoryRoute: InventoryRoute,
  ProcurementRoute: ProcurementRoute,
  QualityRoute: QualityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
